### ISSUE TITLE
Navigating back from specific poll not clearing arrow

### ISSUE THREAD

**Issue by gonditeniz** [Pedro-vk/EthKudos#32]
When you enter a specific poll (current or past) an arrow is shown close to the page title.

That arrow allows going back to the home page by clicking it. However, it doesn't disappear when reaching the home page. Then, they keep cumulating when clicking to visit other polls but just working the original one.

**Comment by Pedro-vk** [comment]
It only affects Firefox. It seems that can be fixed easily with `web-animations-js` polyfill.
