### ISSUE TITLE
Consider adding categories to use to give Kudos instead of numbers.

### ISSUE THREAD

**Issue by abasallo** [Pedro-vk/EthKudos#44]
e.g. S - M - L - XL being 0.25 - 0.5 - 1 - 2 kudos (or any other category set that is appropiate).

**Comment by Pedro-vk** [comment]
Well, the maximum number of kudos that are able to be sent to the same member is variable, so could be a good idea something like 100%, 50%, 25% and 10%, maybe.
For 2 kudos: 2, 1, 0.5 & 0.2.
For 1 kudo: 1, 0.5, 0.25 & 0.1.
If the organization have 1 decimal and the maximum number of kudos is 1, this feature must be hidden.

Thanks for the idea @abasallo!

**Comment by Pedro-vk** [comment]
It looks like (Spanish translation):
![image](https://user-images.githubusercontent.com/1885747/43617588-73f36792-96c3-11e8-8a3f-4c0c6b33ee04.png)
The buttons are:
- Custom (focus the input)
- 10% of max. kudos per member
- 25% of max. kudos per member
- 50% of max. kudos per member
- 100% of max. kudos per member
